package com.example.flagguesser
object BanderasData {
    val lista = listOf(
        BanderaClass("Afganistán", R.drawable.af),
        BanderaClass("Albania", R.drawable.al),
        BanderaClass("Alemania", R.drawable.de),
        BanderaClass("Andorra", R.drawable.ad),
        BanderaClass("Angola", R.drawable.ao),
        BanderaClass("Antigua y Barbuda", R.drawable.ag),
        BanderaClass("Arabia Saudita", R.drawable.sa),
        BanderaClass("Argelia", R.drawable.dz),
        BanderaClass("Argentina", R.drawable.ar),
        BanderaClass("Armenia", R.drawable.am),
        BanderaClass("Australia", R.drawable.au),
        BanderaClass("Austria", R.drawable.at),
        BanderaClass("Azerbaiyán", R.drawable.az),
        BanderaClass("Bahamas", R.drawable.bs),
        BanderaClass("Bangladés", R.drawable.bd),
        BanderaClass("Barbados", R.drawable.bb),
        BanderaClass("Baréin", R.drawable.bh),
        BanderaClass("Bélgica", R.drawable.be),
        BanderaClass("Belice", R.drawable.bz),
        BanderaClass("Benín", R.drawable.bj),
        BanderaClass("Bielorrusia", R.drawable.by),
        BanderaClass("Birmania", R.drawable.mm),
        BanderaClass("Bolivia", R.drawable.bo),
        BanderaClass("Bosnia y Herzegovina", R.drawable.ba),
        BanderaClass("Botsuana", R.drawable.bw),
        BanderaClass("Brasil", R.drawable.br),
        BanderaClass("Brunéi", R.drawable.bn),
        BanderaClass("Bulgaria", R.drawable.bg),
        BanderaClass("Burkina Faso", R.drawable.bf),
        BanderaClass("Burundi", R.drawable.bi),
        BanderaClass("Bután", R.drawable.bt),
        BanderaClass("Cabo Verde", R.drawable.cv),
        BanderaClass("Camboya", R.drawable.kh),
        BanderaClass("Camerún", R.drawable.cm),
        BanderaClass("Canadá", R.drawable.ca),
        BanderaClass("Catar", R.drawable.qa),
        BanderaClass("Chad", R.drawable.td),
        BanderaClass("Chile", R.drawable.cl),
        BanderaClass("China", R.drawable.cn),
        BanderaClass("Chipre", R.drawable.cy),
        BanderaClass("Ciudad del Vaticano", R.drawable.va),
        BanderaClass("Colombia", R.drawable.co),
        BanderaClass("Comoras", R.drawable.km),
        BanderaClass("Corea del Norte", R.drawable.kp),
        BanderaClass("Corea del Sur", R.drawable.kr),
        BanderaClass("Costa de Marfil", R.drawable.ci),
        BanderaClass("Costa Rica", R.drawable.cr),
        BanderaClass("Croacia", R.drawable.hr),
        BanderaClass("Cuba", R.drawable.cu),
        BanderaClass("Dinamarca", R.drawable.dk),
        BanderaClass("Dominica", R.drawable.dm),
        BanderaClass("Ecuador", R.drawable.ec),
        BanderaClass("Egipto", R.drawable.eg),
        BanderaClass("El Salvador", R.drawable.sv),
        BanderaClass("Emiratos Árabes Unidos", R.drawable.ae),
        BanderaClass("Eritrea", R.drawable.er),
        BanderaClass("Eslovaquia", R.drawable.sk),
        BanderaClass("Eslovenia", R.drawable.si),
        BanderaClass("España", R.drawable.es),
        BanderaClass("Estados Unidos", R.drawable.us),
        BanderaClass("Estonia", R.drawable.ee),
        BanderaClass("Esuatini", R.drawable.sz),
        BanderaClass("Etiopía", R.drawable.et),
        BanderaClass("Filipinas", R.drawable.ph),
        BanderaClass("Finlandia", R.drawable.fi),
        BanderaClass("Fiyi", R.drawable.fj),
        BanderaClass("Francia", R.drawable.fr),
        BanderaClass("Gabón", R.drawable.ga),
        BanderaClass("Gambia", R.drawable.gm),
        BanderaClass("Georgia", R.drawable.ge),
        BanderaClass("Ghana", R.drawable.gh),
        BanderaClass("Granada", R.drawable.gd),
        BanderaClass("Grecia", R.drawable.gr),
        BanderaClass("Guatemala", R.drawable.gt),
        BanderaClass("Guinea", R.drawable.gn),
        BanderaClass("Guinea-Bisáu", R.drawable.gw),
        BanderaClass("Guinea Ecuatorial", R.drawable.gq),
        BanderaClass("Guyana", R.drawable.gy),
        BanderaClass("Haití", R.drawable.ht),
        BanderaClass("Honduras", R.drawable.hn),
        BanderaClass("Hungría", R.drawable.hu),
        BanderaClass("India", R.drawable.in_flag),
        BanderaClass("Indonesia", R.drawable.id),
        BanderaClass("Irak", R.drawable.iq),
        BanderaClass("Irán", R.drawable.ir),
        BanderaClass("Irlanda", R.drawable.ie),
        BanderaClass("Islandia", R.drawable.is_flag),
        BanderaClass("Islas Marshall", R.drawable.mh),
        BanderaClass("Islas Salomón", R.drawable.sb),
        BanderaClass("Israel", R.drawable.il),
        BanderaClass("Italia", R.drawable.it),
        BanderaClass("Jamaica", R.drawable.jm),
        BanderaClass("Japón", R.drawable.jp),
        BanderaClass("Jordania", R.drawable.jo),
        BanderaClass("Kazajistán", R.drawable.kz),
        BanderaClass("Kenia", R.drawable.ke),
        BanderaClass("Kirguistán", R.drawable.kg),
        BanderaClass("Kiribati", R.drawable.ki),
        BanderaClass("Kuwait", R.drawable.kw),
        BanderaClass("Laos", R.drawable.la),
        BanderaClass("Lesoto", R.drawable.ls),
        BanderaClass("Letonia", R.drawable.lv),
        BanderaClass("Líbano", R.drawable.lb),
        BanderaClass("Liberia", R.drawable.lr),
        BanderaClass("Libia", R.drawable.ly),
        BanderaClass("Liechtenstein", R.drawable.li),
        BanderaClass("Lituania", R.drawable.lt),
        BanderaClass("Luxemburgo", R.drawable.lu),
        BanderaClass("Macedonia del Norte", R.drawable.mk),
        BanderaClass("Madagascar", R.drawable.mg),
        BanderaClass("Malasia", R.drawable.my),
        BanderaClass("Malaui", R.drawable.mw),
        BanderaClass("Maldivas", R.drawable.mv),
        BanderaClass("Malí", R.drawable.ml),
        BanderaClass("Malta", R.drawable.mt),
        BanderaClass("Marruecos", R.drawable.ma),
        BanderaClass("Mauricio", R.drawable.mu),
        BanderaClass("Mauritania", R.drawable.mr),
        BanderaClass("México", R.drawable.mx),
        BanderaClass("Micronesia", R.drawable.fm),
        BanderaClass("Moldavia", R.drawable.md),
        BanderaClass("Mónaco", R.drawable.mc),
        BanderaClass("Mongolia", R.drawable.mn),
        BanderaClass("Montenegro", R.drawable.me),
        BanderaClass("Mozambique", R.drawable.mz),
        BanderaClass("Namibia", R.drawable.na),
        BanderaClass("Nauru", R.drawable.nr),
        BanderaClass("Nepal", R.drawable.np),
        BanderaClass("Nicaragua", R.drawable.ni),
        BanderaClass("Níger", R.drawable.ne),
        BanderaClass("Nigeria", R.drawable.ng),
        BanderaClass("Noruega", R.drawable.no),
        BanderaClass("Nueva Zelanda", R.drawable.nz),
        BanderaClass("Omán", R.drawable.om),
        BanderaClass("Países Bajos", R.drawable.nl),
        BanderaClass("Pakistán", R.drawable.pk),
        BanderaClass("Palaos", R.drawable.pw),
        BanderaClass("Palestina", R.drawable.ps),
        BanderaClass("Panamá", R.drawable.pa),
        BanderaClass("Papúa Nueva Guinea", R.drawable.pg),
        BanderaClass("Paraguay", R.drawable.py),
        BanderaClass("Perú", R.drawable.pe),
        BanderaClass("Polonia", R.drawable.pl),
        BanderaClass("Portugal", R.drawable.pt),
        BanderaClass("Reino Unido", R.drawable.gb),
        BanderaClass("República Centroafricana", R.drawable.cf),
        BanderaClass("República Checa", R.drawable.cz),
        BanderaClass("República del Congo", R.drawable.cg),
        BanderaClass("República Democrática del Congo", R.drawable.cd),
        BanderaClass("República Dominicana", R.drawable.do_flag),
        BanderaClass("Ruanda", R.drawable.rw),
        BanderaClass("Rumanía", R.drawable.ro),
        BanderaClass("Rusia", R.drawable.ru),
        BanderaClass("Samoa", R.drawable.ws),
        BanderaClass("San Cristóbal y Nieves", R.drawable.kn),
        BanderaClass("San Marino", R.drawable.sm),
        BanderaClass("San Vicente y las Granadinas", R.drawable.vc),
        BanderaClass("Santa Lucía", R.drawable.lc),
        BanderaClass("Santo Tomé y Príncipe", R.drawable.st),
        BanderaClass("Senegal", R.drawable.sn),
        BanderaClass("Serbia", R.drawable.rs),
        BanderaClass("Seychelles", R.drawable.sc),
        BanderaClass("Sierra Leona", R.drawable.sl),
        BanderaClass("Singapur", R.drawable.sg),
        BanderaClass("Siria", R.drawable.sy),
        BanderaClass("Somalia", R.drawable.so),
        BanderaClass("Sri Lanka", R.drawable.lk),
        BanderaClass("Sudáfrica", R.drawable.za),
        BanderaClass("Sudán", R.drawable.sd),
        BanderaClass("Sudán del Sur", R.drawable.ss),
        BanderaClass("Suecia", R.drawable.se),
        BanderaClass("Suiza", R.drawable.ch),
        BanderaClass("Surinam", R.drawable.sr),
        BanderaClass("Tailandia", R.drawable.th),
        BanderaClass("Tanzania", R.drawable.tz),
        BanderaClass("Tayikistán", R.drawable.tj),
        BanderaClass("Timor Oriental", R.drawable.tl),
        BanderaClass("Togo", R.drawable.tg),
        BanderaClass("Tonga", R.drawable.to),
        BanderaClass("Trinidad y Tobago", R.drawable.tt),
        BanderaClass("Túnez", R.drawable.tn),
        BanderaClass("Turkmenistán", R.drawable.tm),
        BanderaClass("Turquía", R.drawable.tr),
        BanderaClass("Tuvalu", R.drawable.tv),
        BanderaClass("Ucrania", R.drawable.ua),
        BanderaClass("Uganda", R.drawable.ug),
        BanderaClass("Uruguay", R.drawable.uy),
        BanderaClass("Uzbekistán", R.drawable.uz),
        BanderaClass("Vanuatu", R.drawable.vu),
        BanderaClass("Venezuela", R.drawable.ve),
        BanderaClass("Vietnam", R.drawable.vn),
        BanderaClass("Yemen", R.drawable.ye),
        BanderaClass("Zambia", R.drawable.zm),
        BanderaClass("Zimbabue", R.drawable.zw)
    )

}